- name: copy wnd shell script to home/bin
  become: true
  become_user: "{{ main_user }}"
  copy:
    src: "files/wnd"
    dest: "~/bin/wnd"
    mode: '0700'

- name: copy wnd bashrc
  become: true
  become_user: "{{ main_user }}"
  copy:
    src: "files/dot-bashrc"
    dest: "~/.wnd/.bashrc"
    mode: '0600'

- name: Ensure bashrc.d directory exists
  become: true
  become_user: "{{ main_user }}"
  file:
    path: "~/.wnd/.bashrc.d"
    state: directory

- name: copy bash default commands
  become: true
  become_user: "{{ main_user }}"
  copy:
    src: "files/default-commands.sh"
    dest: "~/.wnd/.bashrc.d/default-commands.sh"
    mode: '0600'

- name: copy bash aliases
  become: true
  become_user: "{{ main_user }}"
  copy:
    src: "files/aliases.sh"
    dest: "~/.wnd/.bashrc.d/aliases.sh"
    mode: '0600'
