- name: Ensure .desktop file directory for user
  file:
    path: "/home/{{ main_user }}/.local/share/applications"
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "0755"

- name: Copy Files .desktop file to user's applications folder
  copy:
    dest: "/home/{{ main_user }}/.local/share/applications/wnd-files.desktop"
    src: "files/wnd-files.desktop"
    owner: "{{ main_user }}"
    group: "{{ main_user }}"
    mode: "0644"

- name: Install nextcloud talk desktop
  kewlfft.aur.aur:
    name: nextcloud-talk-desktop-bin
    state: present
  become: yes
  become_user: aur_builder
